wandb_version: 1

discount factor:
  desc: null
  value: 0.9
episodes steps:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.16.0
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700737604.953823
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 16
      - 23
      4: 3.10.8
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
